### ISSUE TITLE
 physical constraints resolution

### ISSUE THREAD

**Issue by jmarcellopereira** [OpenSourcePhysics/tracker#50]
How to obtain the resolution of timer, displacement, velocity in the Tracker?

**Comment by dobrown** [comment]
Not an easy question to answer. The "resolution" of your raw position data
is in principle somewhat less than a pixel, and the time resolution is
typically 1/30 sec. But better to think in terms of uncertainty, which
depends on many factors like the lighting, resolution and sharpness of the
video, the care with which the tracks are marked, the calibration of the
scale, possible perspective and/or radial distortions, etc. There is no set
number, you just have to estimate it based on these factors. If you have
multiple videos of the same thing, another option is to measure each
independently and then find the mean and standard error of the
measurements. But this won't include errors due to miscalibration,
distortion, etc, which can sometimes be substantial. Time uncertainty is
almost zero unless you are using a phone that drops occasional frames.
Hope this helps.

**Comment by jmarcellopereira** [comment]
In fact, solving a quantity using software is really complicated. Regarding time, I used the 1/fps ratio, but I don't know if it's right.
